<?php
/**
 * Expression-card service for TBT Notes.
 *
 * Turns blue ("Useful expression") highlights into editable English–Polish mini
 * flashcards generated by OpenAI. Generation mirrors the pink Pronunciation /
 * ElevenLabs design philosophy:
 *
 *  - generation is teacher-only, manual and server-side,
 *  - the OpenAI key lives server-side only (constant or filter),
 *  - the requested text must currently be highlighted blue in the lesson,
 *  - output is stored in a custom table (lesson_id + normalised-text hash),
 *  - a per-user hourly rate limit caps accidental spend.
 *
 * Cards are created as drafts. The teacher is the quality-control gate: students
 * only ever see cards a teacher has explicitly approved.
 *
 * @package TBT_Notes
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class TBT_Notes_Expression_Cards
 */
class TBT_Notes_Expression_Cards {

	/**
	 * Max characters allowed for a single expression.
	 */
	const MAX_TEXT_LENGTH = 200;

	/**
	 * Max generations per user per hour.
	 */
	const RATE_LIMIT = 50;

	/**
	 * Default CEFR level for generated cards.
	 */
	const DEFAULT_LEVEL = 'B1/B2';

	/**
	 * AI provider slug stored on each card.
	 */
	const PROVIDER = 'openai';

	/**
	 * Allowed card statuses.
	 */
	const STATUSES = array( 'draft', 'approved' );

	/* --------------------------------------------------------------------- *
	 * Configuration
	 * --------------------------------------------------------------------- */

	/**
	 * Resolve the OpenAI API key from a PHP constant or a filter. Never exposed to
	 * the front end.
	 *
	 * @return string
	 */
	protected static function openai_api_key() {
		$key = defined( 'TBT_NOTES_OPENAI_API_KEY' ) ? TBT_NOTES_OPENAI_API_KEY : '';
		/**
		 * Filter the OpenAI API key (lets a Code Snippets plugin provide it).
		 *
		 * @param string $key The API key.
		 */
		$key = apply_filters( 'tbt_notes_openai_api_key', $key );
		return is_string( $key ) ? trim( $key ) : '';
	}

	/**
	 * Whether an API key is configured (without revealing it).
	 *
	 * @return bool
	 */
	public static function has_api_key() {
		return '' !== self::openai_api_key();
	}

	/**
	 * Resolve the OpenAI model (constant or filter), defaulting to a small model
	 * suited to this translation + one-example task.
	 *
	 * @return string
	 */
	protected static function openai_model() {
		$model = defined( 'TBT_NOTES_OPENAI_MODEL' ) ? TBT_NOTES_OPENAI_MODEL : 'gpt-5.4-nano';
		/**
		 * Filter the OpenAI model used for expression cards.
		 *
		 * @param string $model The model identifier.
		 */
		$model = apply_filters( 'tbt_notes_openai_model', $model );
		return is_string( $model ) && '' !== trim( $model ) ? trim( $model ) : 'gpt-5.4-nano';
	}

	/* --------------------------------------------------------------------- *
	 * Text helpers (no WordPress dependency — also unit-tested standalone)
	 * --------------------------------------------------------------------- */

	/**
	 * Collapse whitespace runs to single spaces and trim. Canonical form used for
	 * comparison, hashing and storage.
	 *
	 * @param string $text Raw text.
	 * @return string
	 */
	public static function normalize_text( $text ) {
		$text = (string) $text;
		$text = preg_replace( '/\s+/u', ' ', $text );
		if ( null === $text ) {
			// preg failure on invalid UTF-8 — fall back to ASCII-only collapse.
			$text = preg_replace( '/\s+/', ' ', (string) $text );
		}
		return trim( (string) $text );
	}

	/**
	 * Stable hash of the normalised text (used for caching/lookups).
	 *
	 * @param string $text Raw text.
	 * @return string SHA-256 hex.
	 */
	public static function text_hash( $text ) {
		return hash( 'sha256', self::normalize_text( $text ) );
	}

	/**
	 * Character length of the normalised text.
	 *
	 * @param string $text Raw text.
	 * @return int
	 */
	protected static function text_length( $text ) {
		$text = self::normalize_text( $text );
		return function_exists( 'mb_strlen' ) ? mb_strlen( $text, 'UTF-8' ) : strlen( $text );
	}

	/**
	 * Is the (normalised) text longer than the allowed limit?
	 *
	 * @param string $text Raw text.
	 * @return bool
	 */
	public static function exceeds_length_limit( $text ) {
		return self::text_length( $text ) > self::MAX_TEXT_LENGTH;
	}

	/* --------------------------------------------------------------------- *
	 * Blue-highlight extraction (server-side source of truth)
	 * --------------------------------------------------------------------- */

	/**
	 * Extract the distinct blue-highlight (tbt-hl-blue) fragments from a lesson
	 * body: text content, normalised, non-empty, de-duplicated, in document order.
	 * Mirrors the client extractor so teacher and server agree.
	 *
	 * @param string $html Lesson body HTML.
	 * @return string[]
	 */
	public static function extract_blue_highlights( $html ) {
		$html = (string) $html;
		if ( '' === trim( $html ) ) {
			return array();
		}

		$raw = class_exists( 'DOMDocument' )
			? self::extract_blue_dom( $html )
			: self::extract_blue_regex( $html );

		$out  = array();
		$seen = array();
		foreach ( $raw as $text ) {
			$norm = self::normalize_text( $text );
			if ( '' === $norm || isset( $seen[ $norm ] ) ) {
				continue;
			}
			$seen[ $norm ] = true;
			$out[]         = $norm;
		}
		return $out;
	}

	/**
	 * DOM-based extraction of blue-highlight text.
	 *
	 * @param string $html Lesson body HTML.
	 * @return string[]
	 */
	protected static function extract_blue_dom( $html ) {
		// Encode non-ASCII as numeric entities so DOMDocument keeps UTF-8.
		$wrapped = '<div data-tbt-root="1">' . $html . '</div>';
		if ( function_exists( 'mb_encode_numericentity' ) ) {
			$wrapped = mb_encode_numericentity( $wrapped, array( 0x80, 0x10FFFF, 0, 0x10FFFF ), 'UTF-8' );
		}

		$dom = new DOMDocument();
		libxml_use_internal_errors( true );
		$dom->loadHTML( $wrapped, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD );
		libxml_clear_errors();

		$xpath = new DOMXPath( $dom );
		$nodes = $xpath->query( "//*[contains(concat(' ', normalize-space(@class), ' '), ' tbt-hl-blue ')]" );

		$out = array();
		if ( $nodes ) {
			foreach ( $nodes as $node ) {
				$out[] = $node->textContent;
			}
		}
		return $out;
	}

	/**
	 * Regex fallback used only when ext-dom is unavailable.
	 *
	 * @param string $html Lesson body HTML.
	 * @return string[]
	 */
	protected static function extract_blue_regex( $html ) {
		$out = array();
		if ( preg_match_all( '/<([a-z0-9]+)\b[^>]*class="[^"]*\btbt-hl-blue\b[^"]*"[^>]*>(.*?)<\/\1>/is', $html, $m ) ) {
			foreach ( $m[2] as $inner ) {
				$inner = preg_replace( '/<[^>]*>/', '', $inner );
				$out[] = html_entity_decode( $inner, ENT_QUOTES, 'UTF-8' );
			}
		}
		return $out;
	}

	/* --------------------------------------------------------------------- *
	 * Context extraction (gives the model the surrounding sentence)
	 * --------------------------------------------------------------------- */

	/**
	 * Convert lesson body HTML to normalised plain text.
	 *
	 * @param string $html Lesson body HTML.
	 * @return string
	 */
	protected static function plain_text_from_html( $html ) {
		$html = (string) $html;
		if ( '' === trim( $html ) ) {
			return '';
		}
		// Put spaces where block boundaries were so words don't run together.
		$html = preg_replace( '/<(br|\/p|\/li|\/h[1-6]|\/div|\/blockquote)\s*>/i', ' ', $html );
		$text = wp_strip_all_tags( $html );
		$text = html_entity_decode( $text, ENT_QUOTES, 'UTF-8' );
		return self::normalize_text( $text );
	}

	/**
	 * Build a short context window around the highlighted term: roughly $limit
	 * characters before and after the first occurrence in the lesson's plain text.
	 * Falls back to the term itself if it cannot be located.
	 *
	 * @param string $html  Lesson body HTML.
	 * @param string $text  Normalised highlighted term.
	 * @param int    $limit Characters of context on each side.
	 * @return string
	 */
	protected static function extract_context_for_text( $html, $text, $limit = 220 ) {
		$plain = self::plain_text_from_html( $html );
		$term  = self::normalize_text( $text );
		if ( '' === $plain || '' === $term ) {
			return $term;
		}

		$lower_plain = function_exists( 'mb_strtolower' ) ? mb_strtolower( $plain, 'UTF-8' ) : strtolower( $plain );
		$lower_term  = function_exists( 'mb_strtolower' ) ? mb_strtolower( $term, 'UTF-8' ) : strtolower( $term );

		$pos = function_exists( 'mb_strpos' ) ? mb_strpos( $lower_plain, $lower_term, 0, 'UTF-8' ) : strpos( $lower_plain, $lower_term );
		if ( false === $pos ) {
			return $term;
		}

		$term_len = function_exists( 'mb_strlen' ) ? mb_strlen( $term, 'UTF-8' ) : strlen( $term );
		$start    = max( 0, $pos - $limit );
		$length   = $term_len + ( $limit * 2 ) + ( $pos - $start );

		$slice = function_exists( 'mb_substr' )
			? mb_substr( $plain, $start, $length, 'UTF-8' )
			: substr( $plain, $start, $length );

		return self::normalize_text( $slice );
	}

	/* --------------------------------------------------------------------- *
	 * Listing for the REST layer
	 * --------------------------------------------------------------------- */

	/**
	 * Build the expression-card list for a lesson.
	 *
	 * Teacher: every current blue highlight, each flagged with whether a card
	 * exists (and its current contents). Student: only current blue highlights
	 * that already have an approved card.
	 *
	 * @param int  $lesson_id   Lesson ID.
	 * @param bool $for_teacher Whether the viewer can manage notes.
	 * @return array[]
	 */
	public static function list_for_lesson( $lesson_id, $for_teacher ) {
		$lesson = TBT_Notes_DB::get_lesson( (int) $lesson_id );
		if ( ! $lesson ) {
			return array();
		}

		$records = TBT_Notes_DB::get_expression_cards_for_lesson( (int) $lesson_id );
		$by_hash = array();
		foreach ( $records as $rec ) {
			$by_hash[ $rec['text_hash'] ] = $rec;
		}

		$blue = self::extract_blue_highlights( $lesson['body'] );
		$out  = array();

		foreach ( $blue as $text ) {
			$hash = self::text_hash( $text );
			$rec  = isset( $by_hash[ $hash ] ) ? $by_hash[ $hash ] : null;

			if ( $for_teacher ) {
				if ( $rec ) {
					$out[] = array(
						'text'               => $text,
						'has_card'           => true,
						'card_id'            => (int) $rec['id'],
						'polish_translation' => $rec['polish_translation'],
						'example_sentence'   => $rec['example_sentence'],
						'level'              => $rec['level'],
						'status'             => $rec['status'],
						'can_generate'       => true,
					);
				} else {
					$out[] = array(
						'text'         => $text,
						'has_card'     => false,
						'can_generate' => true,
					);
				}
			} elseif ( $rec && 'approved' === $rec['status'] ) {
				// Students only ever see approved, currently-blue items.
				$out[] = array(
					'text'               => $text,
					'has_card'           => true,
					'polish_translation' => $rec['polish_translation'],
					'example_sentence'   => $rec['example_sentence'],
					'level'              => $rec['level'],
					'status'             => 'approved',
				);
			}
		}

		return $out;
	}

	/* --------------------------------------------------------------------- *
	 * Generation
	 * --------------------------------------------------------------------- */

	/**
	 * Generate (or reuse/regenerate) a card for one blue-highlight item.
	 *
	 * @param int    $lesson_id Lesson ID.
	 * @param string $text      Requested text (must be a current blue highlight).
	 * @param bool   $force     Force regeneration even if a card already exists.
	 * @return array|WP_Error Shaped card record, or an error.
	 */
	public static function generate( $lesson_id, $text, $force = false ) {
		$lesson_id = (int) $lesson_id;
		$lesson    = TBT_Notes_DB::get_lesson( $lesson_id );
		if ( ! $lesson ) {
			return new WP_Error( 'tbt_notes_not_found', __( 'Lesson not found.', 'tbt-notes' ), array( 'status' => 404 ) );
		}

		$norm = self::normalize_text( $text );
		if ( '' === $norm ) {
			return new WP_Error( 'tbt_notes_expr_empty', __( 'There is no text to generate a card for.', 'tbt-notes' ), array( 'status' => 400 ) );
		}
		if ( self::exceeds_length_limit( $norm ) ) {
			return new WP_Error( 'tbt_notes_expr_too_long', __( 'This expression is too long to generate a card.', 'tbt-notes' ), array( 'status' => 400 ) );
		}

		// Source of truth: the text must currently be a blue highlight.
		if ( ! in_array( $norm, self::extract_blue_highlights( $lesson['body'] ), true ) ) {
			return new WP_Error( 'tbt_notes_expr_not_blue', __( 'This text is no longer marked as a useful expression.', 'tbt-notes' ), array( 'status' => 400 ) );
		}

		$hash     = self::text_hash( $norm );
		$existing = TBT_Notes_DB::get_expression_card( $lesson_id, $hash );

		// Reuse the existing card unless the teacher explicitly regenerates.
		if ( $existing && ! $force ) {
			return $existing;
		}

		$key = self::openai_api_key();
		if ( '' === $key ) {
			return new WP_Error( 'tbt_notes_no_api_key', __( 'OpenAI API key is not configured.', 'tbt-notes' ), array( 'status' => 500 ) );
		}

		$rate = self::check_rate_limit();
		if ( is_wp_error( $rate ) ) {
			return $rate;
		}

		$context = self::extract_context_for_text( $lesson['body'], $norm );

		$result = self::call_openai(
			array(
				'term'         => $norm,
				'context'      => $context,
				'lesson_title' => (string) $lesson['header'],
				'level'        => self::DEFAULT_LEVEL,
			)
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		self::bump_rate_limit();

		$model = self::openai_model();

		if ( $existing ) {
			// Regeneration: refresh content and reset to draft for re-approval.
			$ok = TBT_Notes_DB::update_expression_card(
				(int) $existing['id'],
				array(
					'context'            => $context,
					'polish_translation' => $result['polish_translation'],
					'example_sentence'   => $result['example_sentence'],
					'level'              => self::DEFAULT_LEVEL,
					'status'             => 'draft',
					'provider'           => self::PROVIDER,
					'model'              => $model,
				)
			);
			if ( false === $ok ) {
				return new WP_Error( 'tbt_notes_expr_db', __( 'Could not generate the expression card. Please try again.', 'tbt-notes' ), array( 'status' => 500 ) );
			}
			return TBT_Notes_DB::get_expression_card_by_id( (int) $existing['id'] );
		}

		$card_id = TBT_Notes_DB::insert_expression_card(
			array(
				'lesson_id'          => $lesson_id,
				'text_hash'          => $hash,
				'text'               => $norm,
				'context'            => $context,
				'polish_translation' => $result['polish_translation'],
				'example_sentence'   => $result['example_sentence'],
				'level'              => self::DEFAULT_LEVEL,
				'status'             => 'draft',
				'provider'           => self::PROVIDER,
				'model'              => $model,
			)
		);

		if ( ! $card_id ) {
			return new WP_Error( 'tbt_notes_expr_db', __( 'Could not generate the expression card. Please try again.', 'tbt-notes' ), array( 'status' => 500 ) );
		}

		return TBT_Notes_DB::get_expression_card_by_id( $card_id );
	}

	/**
	 * Apply teacher edits to a card. Validates status strictly. Returns the
	 * refreshed card (or a WP_Error).
	 *
	 * @param int   $card_id Card ID.
	 * @param array $fields  Any of: polish_translation, example_sentence, status.
	 * @return array|WP_Error
	 */
	public static function update_card( $card_id, array $fields ) {
		$card_id = (int) $card_id;
		$card    = TBT_Notes_DB::get_expression_card_by_id( $card_id );
		if ( ! $card ) {
			return new WP_Error( 'tbt_notes_not_found', __( 'Expression card not found.', 'tbt-notes' ), array( 'status' => 404 ) );
		}

		$data = array();

		if ( array_key_exists( 'polish_translation', $fields ) ) {
			$value = self::clean_field( $fields['polish_translation'] );
			if ( '' === $value ) {
				return new WP_Error( 'tbt_notes_expr_invalid', __( 'The Polish translation cannot be empty.', 'tbt-notes' ), array( 'status' => 400 ) );
			}
			$data['polish_translation'] = $value;
		}

		if ( array_key_exists( 'example_sentence', $fields ) ) {
			$value = self::clean_field( $fields['example_sentence'] );
			if ( '' === $value ) {
				return new WP_Error( 'tbt_notes_expr_invalid', __( 'The example sentence cannot be empty.', 'tbt-notes' ), array( 'status' => 400 ) );
			}
			$data['example_sentence'] = $value;
		}

		if ( array_key_exists( 'status', $fields ) ) {
			$status = is_string( $fields['status'] ) ? trim( $fields['status'] ) : '';
			if ( ! in_array( $status, self::STATUSES, true ) ) {
				return new WP_Error( 'tbt_notes_expr_status', __( 'Invalid card status.', 'tbt-notes' ), array( 'status' => 400 ) );
			}
			$data['status'] = $status;
		}

		if ( empty( $data ) ) {
			return $card;
		}

		$ok = TBT_Notes_DB::update_expression_card( $card_id, $data );
		if ( false === $ok ) {
			return new WP_Error( 'tbt_notes_expr_db', __( 'Could not save the expression card. Please try again.', 'tbt-notes' ), array( 'status' => 500 ) );
		}

		return TBT_Notes_DB::get_expression_card_by_id( $card_id );
	}

	/**
	 * Approve a card (set status = approved). Returns the refreshed card.
	 *
	 * @param int $card_id Card ID.
	 * @return array|WP_Error
	 */
	public static function approve_card( $card_id ) {
		return self::update_card( (int) $card_id, array( 'status' => 'approved' ) );
	}

	/**
	 * Reduce an AI/teacher field to safe, single-line plain text.
	 *
	 * @param mixed $value Raw value.
	 * @return string
	 */
	protected static function clean_field( $value ) {
		$value = is_string( $value ) ? $value : '';
		if ( function_exists( 'sanitize_text_field' ) ) {
			$value = sanitize_text_field( $value );
		} else {
			$value = trim( preg_replace( '/\s+/', ' ', wp_strip_all_tags( $value ) ) );
		}
		return $value;
	}

	/* --------------------------------------------------------------------- *
	 * OpenAI call + parsing
	 * --------------------------------------------------------------------- */

	/**
	 * Call the OpenAI Responses API with a strict JSON-schema structured output.
	 *
	 * @param array $payload_context term, context, lesson_title, level.
	 * @return array|WP_Error array{polish_translation:string,example_sentence:string}.
	 */
	protected static function call_openai( array $payload_context ) {
		$key   = self::openai_api_key();
		$model = self::openai_model();

		$term         = isset( $payload_context['term'] ) ? (string) $payload_context['term'] : '';
		$context      = isset( $payload_context['context'] ) ? (string) $payload_context['context'] : '';
		$lesson_title = isset( $payload_context['lesson_title'] ) ? (string) $payload_context['lesson_title'] : '';
		$level        = isset( $payload_context['level'] ) ? (string) $payload_context['level'] : self::DEFAULT_LEVEL;

		$prompt = "Term:\n{$term}\n\n"
			. "Lesson title:\n{$lesson_title}\n\n"
			. "Context:\n{$context}\n\n"
			. "Student level:\n{$level}\n\n"
			. "Rules:\n"
			. "- Translate the meaning in this context, not every possible meaning.\n"
			. "- Use natural Polish, not a literal translation.\n"
			. "- If two natural Polish versions are useful, separate them with \" / \".\n"
			. "- The example sentence must be in English.\n"
			. "- The example sentence must be B1/B2 level.\n"
			. "- The example sentence must clearly show the same meaning as in the context.\n"
			. "- Avoid complicated grammar unless necessary.\n"
			. "- Do not mention the lesson, teacher, app, AI, or context.\n"
			. "- Do not add explanations, notes, markdown, or extra fields.";

		$body = array(
			'model' => $model,
			'input' => array(
				array(
					'role'    => 'system',
					'content' => array(
						array(
							'type' => 'input_text',
							'text' => 'You generate small English-Polish flashcards for adult Polish learners of English. Return only the required JSON fields. Follow the schema exactly.',
						),
					),
				),
				array(
					'role'    => 'user',
					'content' => array(
						array(
							'type' => 'input_text',
							'text' => $prompt,
						),
					),
				),
			),
			'text'  => array(
				'format' => array(
					'type'                 => 'json_schema',
					'name'                 => 'tbt_expression_card',
					'strict'               => true,
					'schema'               => array(
						'type'                 => 'object',
						'additionalProperties' => false,
						'required'             => array( 'polish_translation', 'example_sentence' ),
						'properties'           => array(
							'polish_translation' => array(
								'type'        => 'string',
								'description' => 'Natural Polish translation of the English expression in the given context.',
							),
							'example_sentence'   => array(
								'type'        => 'string',
								'description' => 'One clear English example sentence at B1/B2 level.',
							),
						),
					),
				),
			),
		);

		$response = wp_remote_post(
			'https://api.openai.com/v1/responses',
			array(
				'timeout' => 45,
				'headers' => array(
					'Authorization' => 'Bearer ' . $key,
					'Content-Type'  => 'application/json',
				),
				'body'    => wp_json_encode( $body ),
			)
		);

		if ( is_wp_error( $response ) ) {
			return new WP_Error( 'tbt_notes_expr_http', __( 'Could not generate the expression card. Please try again.', 'tbt-notes' ), array( 'status' => 502 ) );
		}

		$code = (int) wp_remote_retrieve_response_code( $response );
		$raw  = wp_remote_retrieve_body( $response );
		if ( 200 !== $code || '' === $raw ) {
			return new WP_Error( 'tbt_notes_expr_api', __( 'Could not generate the expression card. Please try again.', 'tbt-notes' ), array( 'status' => 502 ) );
		}

		return self::parse_openai_response( $raw );
	}

	/**
	 * Parse the OpenAI Responses API body into the two required fields. Robust to
	 * the various shapes the Responses API can return.
	 *
	 * @param string $response Raw JSON response body.
	 * @return array|WP_Error array{polish_translation:string,example_sentence:string}.
	 */
	protected static function parse_openai_response( $response ) {
		$decoded = json_decode( (string) $response, true );
		if ( ! is_array( $decoded ) ) {
			return self::parse_error();
		}

		$json_text = '';

		// 1. Prefer a flattened output_text if the API provided one.
		if ( isset( $decoded['output_text'] ) && is_string( $decoded['output_text'] ) && '' !== trim( $decoded['output_text'] ) ) {
			$json_text = $decoded['output_text'];
		} elseif ( isset( $decoded['output_text'] ) && is_array( $decoded['output_text'] ) ) {
			$json_text = implode( '', array_filter( $decoded['output_text'], 'is_string' ) );
		}

		// 2. Otherwise walk output[] -> content[] for the first text payload.
		if ( '' === trim( $json_text ) && isset( $decoded['output'] ) && is_array( $decoded['output'] ) ) {
			foreach ( $decoded['output'] as $item ) {
				if ( ! is_array( $item ) || empty( $item['content'] ) || ! is_array( $item['content'] ) ) {
					continue;
				}
				foreach ( $item['content'] as $chunk ) {
					if ( is_array( $chunk ) && isset( $chunk['text'] ) && is_string( $chunk['text'] ) && '' !== trim( $chunk['text'] ) ) {
						$json_text = $chunk['text'];
						break 2;
					}
				}
			}
		}

		if ( '' === trim( $json_text ) ) {
			return self::parse_error();
		}

		$payload = json_decode( $json_text, true );
		if ( ! is_array( $payload )
			|| ! isset( $payload['polish_translation'], $payload['example_sentence'] )
			|| ! is_string( $payload['polish_translation'] )
			|| ! is_string( $payload['example_sentence'] ) ) {
			return self::parse_error();
		}

		$polish  = self::clean_field( $payload['polish_translation'] );
		$example = self::clean_field( $payload['example_sentence'] );

		if ( '' === $polish || '' === $example ) {
			return self::parse_error();
		}

		return array(
			'polish_translation' => $polish,
			'example_sentence'   => $example,
		);
	}

	/**
	 * Shared "could not read the AI response" error.
	 *
	 * @return WP_Error
	 */
	protected static function parse_error() {
		return new WP_Error( 'tbt_notes_expr_parse', __( 'Could not read the AI response. Please try again.', 'tbt-notes' ), array( 'status' => 502 ) );
	}

	/* --------------------------------------------------------------------- *
	 * Rate limiting (per user, per hour)
	 * --------------------------------------------------------------------- */

	/**
	 * Transient key for the current user's hourly counter.
	 *
	 * @return string
	 */
	protected static function rate_key() {
		return 'tbt_notes_expr_rl_' . get_current_user_id();
	}

	/**
	 * Refuse generation if the user is over their hourly quota.
	 *
	 * @return true|WP_Error
	 */
	protected static function check_rate_limit() {
		$count = (int) get_transient( self::rate_key() );
		if ( $count >= self::RATE_LIMIT ) {
			return new WP_Error( 'tbt_notes_expr_rate', __( 'You have reached the hourly expression-card generation limit. Please try again later.', 'tbt-notes' ), array( 'status' => 429 ) );
		}
		return true;
	}

	/**
	 * Increment the current user's hourly counter.
	 */
	protected static function bump_rate_limit() {
		$key   = self::rate_key();
		$count = (int) get_transient( $key );
		set_transient( $key, $count + 1, HOUR_IN_SECONDS );
	}
}
